# Variables to be passed into your templates and default values.
dbUserOdoo:
  username: ""
  password: ""

odooAppCredentials:
  adminUser: ""
  adminPassword: ""
  masterPassword: ""

odooInstance:
  odoo:
    env:
      dbReadyDelay: "2"
      maxDbReadyRetries: "30"
      initDelay: "2"
      maxInitRetries: "100"
    image:
      repository: localhost:30100/odoo/odoo
      tag: 19.0-1
    imagePullPolicy: Always
  
odooDomainFilter:
  hostname: ""

odooStorage:
  dbStorage: 5Gi
  fileStorage: 5Gi
  addonStorage: 5Gi
