# Variables to be passed into your templates and default values.
dbUserOdoo:
  password: ""
  username: ""

odooAppCredentials:
  adminPassword: ""
  adminUser: ""
  masterPassword: ""

odooInstance:
  odoo:
    env:
      dbReadyDelay: "2"
      maxDbReadyRetries: "30"
      initDelay: "2"
      maxInitRetries: "1000"
    image:
      repository: localhost:30100/odoo/odoo
      tag: 19.0-1
    imagePullPolicy: Always
  
